theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: none
  summary:
    position: hero
  posts:
    date_format: "2006"
    index:
      truncate_description: 0
      layout: grid
      options:
        categories: false