theme: osuny
_merge: deep
params:
  breadcrumb:
    position: none
  summary:
    position: hero
  posts:
    date_format: "2006"
    index:
      truncate_description: 0
      layout: grid
      options:
        categories: false