[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/livres/heterodoxies/"
to = "/livres/heterodoxie/"

[[redirects]]
from = "/equipe/marie-real/"
to = "/personnes/marie-real/"

[[redirects]]
from = "/equipe/"
to = "/personnes/"

[[redirects]]
from = "/equipe/david-s-evans/"
to = "/personnes/david-s-evans/"

[[redirects]]
from = "/actualites/2016-05-24-matchmakers/"
to = "/livres/2016-05-24-matchmakers/"

[[redirects]]
from = "/equipe/antoine-mestrallet/"
to = "/personnes/antoine-mestrallet/"

[[redirects]]
from = "/equipe/antoine-kurka/"
to = "/personnes/antoine-kurka/"

[[redirects]]
from = "/equipe/dominique-cardon/"
to = "/personnes/dominique-cardon/"

[[redirects]]
from = "/equipe/richard-schmalensee/"
to = "/personnes/richard-schmalensee/"

[[redirects]]
from = "/actualites/2015-10-01-a-quoi-revent-les-algorithmes/"
to = "/livres/2015-10-01-a-quoi-revent-les-algorithmes/"

[[redirects]]
from = "/equipe/equipe-editoriale/"
to = "/personnes/equipe-editoriale/"

[[redirects]]
from = "/actualites/"
to = "/livres/"

[[redirects]]
from = "/equipe/hartmut-rosa/"
to = "/personnes/hartmut-rosa/"

[[redirects]]
from = "/equipe/kevin-echraghi/"
to = "/personnes/kevin-echraghi/"

